// Generated by CoffeeScript 1.9.0
(function() {
  var $iframeIndex, changeSlide, disableIframe, enableIframe, _base;

  window.slides || (window.slides = {});

  (_base = window.slides).transition || (_base.transition = 500);

  window.slides.$visibleIframes = null;

  $iframeIndex = {};

  disableIframe = function(iframe) {
    var src;
    if ($(iframe).data('src')) {
      return;
    }
    src = $(iframe).attr('src');
    $(iframe).data('src', src);
    iframe.onload = null;
    return iframe.src = 'about:blank';
  };

  enableIframe = function(iframe) {
    var src;
    src = $(iframe).data('src');
    if (!src) {
      return;
    }
    iframe.src = src;
    return $(iframe).data('src', null);
  };

  changeSlide = function(e, from, to) {
    var $slide, getTopSlide;
    getTopSlide = function(step) {
      var $parents, $slide;
      $slide = $.deck('getSlide', step);
      $parents = $slide.parents('.slide');
      if ($parents.length) {
        return $parents;
      } else {
        return $slide;
      }
    };
    $slide = getTopSlide(to);
    slides.$visibleIframes = $slide.find('iframe');
    $slide.find('video').each(function() {
      return this.play();
    });
    $slide.find('iframe').each(function() {
      if (!$(this).hasClass('autoplay')) {
        return;
      }
      if (!/youtube\.com/.test($(this).attr('src'))) {
        return;
      }
      return this.contentWindow.postMessage('{"event":"command","func":"playVideo","args":""}', '*');
    });
    setTimeout((function() {
      $.deck('getSlide', from).find('video').each(function() {
        return this.pause();
      });
      return $.deck('getSlide', from).find('iframe').each(function() {
        if (!/youtube\.com/.test($(this).attr('src'))) {
          return;
        }
        return this.contentWindow.postMessage('{"event":"command","func":"pauseVideo","args":""}', '*');
      });
    }), slides.transition / 2);
    $iframeIndex[to].forEach(function(iframe) {
      return enableIframe(iframe);
    });
    return $('iframe').not($iframeIndex[to]).each(function() {
      var iframe;
      iframe = this;
      return setTimeout((function() {
        return disableIframe(iframe);
      }), slides.transition / 2);
    });
  };

  $(function() {
    $('.slide').each(function(i) {
      var $iframes, $parents, $this;
      $this = $(this);
      $parents = $this.parents('.slide');
      if ($parents.length) {
        $this = $parents;
      }
      $iframes = $this.find('iframe');
      return [i - 1, i, i + 1].forEach(function(i) {
        $iframeIndex[i] || ($iframeIndex[i] = []);
        return $iframes.each(function() {
          return $iframeIndex[i].push(this);
        });
      });
    });
    $('iframe').each(function() {
      return disableIframe(this);
    });
    return $(document).bind('deck.change', changeSlide);
  });

}).call(this);
