// Generated by CoffeeScript 1.9.0
(function() {
  var $IFRAME_INDEX, $visibleIframes, TRANSITION, changeSlide, mathboxGo, mathboxSpeed, slomo;

  TRANSITION = 300;

  $IFRAME_INDEX = {};

  $visibleIframes = null;

  mathboxGo = function(iframe, step) {
    if (!iframe.contentWindow) {
      return;
    }
    return iframe.contentWindow.postMessage({
      mbgo: step
    }, '*');
  };

  mathboxSpeed = function(iframe, speed) {
    if (!iframe.contentWindow) {
      return;
    }
    return iframe.contentWindow.postMessage({
      mbspeed: speed
    }, '*');
  };

  slomo = function(e) {
    var speed;
    $('body')[e.shiftKey ? 'addClass' : 'removeClass']('slomo');
    speed = e.shiftKey ? .2 : 1;
    if (!$visibleIframes) {
      return;
    }
    return $visibleIframes.each(function() {
      return mathboxSpeed(this, speed);
    });
  };

  changeSlide = function(e, from, to) {
    var $parents, $slide, $subslide, step, whichEnd;
    $subslide = $.deck('getSlide', to);
    $parents = $subslide.parents('.slide');
    $slide = $parents.length ? $parents : $subslide;
    $visibleIframes = $slide.find('iframe');
    step = $slide.find('.slide').index($subslide) + 2;
    $visibleIframes.each(function() {
      return mathboxGo(this, step);
    });
    whichEnd = to > from ? 1 : -1;
    return $IFRAME_INDEX[to].forEach(function(iframe) {
      return setTimeout((function() {
        return iframe.onload = function() {
          iframe.onload = null;
          return mathboxGo(iframe, step);
        };
      }), TRANSITION);
    });
  };

  $(function() {
    $('.slide').each(function(i) {
      var $parents, $this;
      $this = $(this);
      $parents = $this.parents('.slide');
      if ($parents.length) {
        $this = $parents;
      }
      return [i - 1, i, i + 1].forEach(function(i) {
        $IFRAME_INDEX[i] || ($IFRAME_INDEX[i] = []);
        return $this.find('iframe').each(function() {
          return $IFRAME_INDEX[i].push(this);
        });
      });
    });
    $(document).keydown(slomo).keyup(slomo);
    return $(document).bind('deck.change', changeSlide);
  });

}).call(this);
