// Generated by CoffeeScript 1.9.0
(function() {
  var changeSlide, mathboxGo, mathboxSpeed, slomo;

  mathboxGo = function(iframe, step) {
    if (!iframe.contentWindow) {
      return;
    }
    return iframe.contentWindow.postMessage({
      mbgo: step
    }, '*');
  };

  mathboxSpeed = function(iframe, speed) {
    if (!iframe.contentWindow) {
      return;
    }
    return iframe.contentWindow.postMessage({
      mbspeed: speed
    }, '*');
  };

  slomo = function(e) {
    var speed;
    $('body')[e.shiftKey ? 'addClass' : 'removeClass']('slomo');
    speed = e.shiftKey ? .2 : 1;
    if (!slides.$visibleIframes) {
      return;
    }
    return slides.$visibleIframes.each(function() {
      return mathboxSpeed(this, speed);
    });
  };

  changeSlide = function(e, from, to) {
    var $parents, $subslide, $topslide, step, whichEnd;
    $subslide = $.deck('getSlide', to);
    $parents = $subslide.parents('.slide');
    $topslide = $parents.length ? $parents : $subslide;
    step = $topslide.find('.slide').index($subslide) + 2;
    slides.$visibleIframes.each(function() {
      return mathboxGo(this, step);
    });
    whichEnd = to > from ? 1 : -1;
    return slides.$iframeIndex[to].forEach(function(iframe) {
      return setTimeout((function() {
        return iframe.onload = function() {
          iframe.onload = null;
          return mathboxGo(iframe, step);
        };
      }), slides.transition);
    });
  };

  $(function() {
    $(document).keydown(slomo).keyup(slomo);
    return $(document).bind('deck.change', changeSlide);
  });

}).call(this);
